#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Make sure we have npm dependencies installed (the dry run is ~150 ms, which is slow, but tolerable)
if [[ "$(npm install --ignore-scripts --dry-run | grep 'up to date')" = "" ]]; then
  echo "Installing npm dependencies..."
  npm install
fi

# Run devmoji to lint the commit message
npx devmoji -e --lint
