name: Build and Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.3', '>1.21.3' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Tests
        shell: bash
        run: go test -race -coverprofile=cover.out -covermode=atomic ./...

      - name: Report CodeCov
        if: ${{ startsWith(matrix.go-version, '>') }}
        uses: codecov/codecov-action@v4-beta
        with:
          file: ./cover.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Report Lint Errors
        shell: bash
        run: ./lint.sh -v --out-format github-actions
